//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalId { get; set; }
        public double Base { get; set; }
        public double Extras { get; set; }
        public double Finaly { get; set; }
    
        public virtual Workers Workers { get; set; }
    }
}
